### ISSUE TITLE
Wishlist: PV/UV 统计功能

### ISSUE THREAD

**Issue by iminders** [tradingAI/tweb#12]
方式一:  [百度统计](https://tongji.baidu.com/web/10000138381/overview/index?siteId=14351937)
方式二：开发自己的dashboard, 可以做到更精细，实时性更好

**Comment by SnakeHacker** [comment]
Done

**Comment by SnakeHacker** [comment]
方式一 完成，方式二后期在弄，暂时优先级不高

**Comment by SnakeHacker** [comment]
@iminders Closed
