### ISSUE TITLE
Wishlist: 实时job日志收集平台

### ISSUE THREAD

**Issue by iminders** [tradingAI/tweb#18]
Filebeat and Elastic Stack(ELK)

blog:  [logz.io](https://logz.io/learn/complete-guide-elk-stack/#intro)

配置参考：
-  https://github.com/iminders/services/tree/master/starter/kibana
- https://github.com/deviantony/docker-elk/blob/master/docker-compose.yml

**Comment by SnakeHacker** [comment]
这个应该放在tradingAI/runner？

**Comment by iminders** [comment]
嵌入查询页面到tweb中
kibana url 在 secrets.KIBANA_URL 中 @SnakeHacker 

由于服务器性能的问题，kibana服务现在不太稳定，有可能来不及打上去，所以暂时允许log loss的情况

**Comment by SnakeHacker** [comment]
@SnakeHacker  一个文件夹 elk 放到devops项目中
